# Generated by Django 3.0.5 on 2020-04-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0003_auto_20200413_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plotpart',
            options={'ordering': ['position_in_course']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
