# Generated by Django 3.0.5 on 2020-04-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0004_auto_20200415_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['position_in_plot_part']},
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='message_after_correct_answer',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='message_after_incorrect_answer',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='initial_adventure',
        ),
        migrations.AddField(
            model_name='adventure',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golfplatz.Chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventure',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='message_after_correct_answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='message_after_incorrect_answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adventure',
            name='point_source',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='golfplatz.PointSource'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('plot_part', 'position_in_plot_part'), name='position_in_plot_part_constraint'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('name', 'plot_part'), name='chapter_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.UniqueConstraint(fields=('course', 'group_name'), name='group_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='plotpart',
            constraint=models.UniqueConstraint(fields=('course', 'position_in_course'), name='position_in_course_constraint'),
        ),
        migrations.AddConstraint(
            model_name='plotpart',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='plot_part_name_constraint'),
        ),
    ]
