# Generated by Django 3.0.5 on 2020-04-30 14:11
from django.contrib.auth.models import Group
from django.db import migrations


def create_user_groups(apps, schema_editor):
    Group.objects.create(pk=1, name='student')
    Group.objects.create(pk=2, name='tutor')


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0005_auto_20200415_1749'),
    ]

    operations = [
        migrations.RunPython(create_user_groups)
    ]
