# Generated by Django 3.0.5 on 2020-04-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0006_auto_20200430_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='golfplatz.Course'),
        ),
        migrations.AlterField(
            model_name='plotpart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_parts', to='golfplatz.Course'),
        ),
        migrations.AddConstraint(
            model_name='adventure',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='adventure_name_constraint'),
        ),
    ]
