# Generated by Django 3.0.5 on 2020-05-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0007_auto_20200430_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='has_time_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='plot_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='golfplatz.PlotPart'),
        ),
    ]
