# Generated by Django 3.0.5 on 2020-05-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0008_auto_20200501_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='golfplatz.Chapter'),
        ),
    ]
