# Generated by Django 3.0.5 on 2020-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0009_auto_20200504_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
    ]
