# Generated by Django 3.0.5 on 2020-05-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0010_adventure_is_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocheckedgrade',
            name='question',
        ),
        migrations.RemoveField(
            model_name='autocheckedgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='autocheckedpointsource',
            name='pointsource_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='auto_checked_grades',
        ),
        migrations.RemoveField(
            model_name='question',
            name='point_source',
        ),
        migrations.RemoveField(
            model_name='surpriseexercise',
            name='autocheckedpointsource_ptr',
        ),
        migrations.RemoveField(
            model_name='tutorcheckedgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tutorcheckedgrade',
            name='tutor_checked_source',
        ),
        migrations.RemoveField(
            model_name='tutorcheckedpointsource',
            name='pointsource_ptr',
        ),
        migrations.RemoveField(
            model_name='tutorcheckedpointsource',
            name='tutor_checked_grades',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='point_source',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AutoCheckedGrade',
        ),
        migrations.DeleteModel(
            name='AutoCheckedPointSource',
        ),
        migrations.DeleteModel(
            name='PointSource',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SurpriseExercise',
        ),
        migrations.DeleteModel(
            name='TutorCheckedGrade',
        ),
        migrations.DeleteModel(
            name='TutorCheckedPointSource',
        ),
    ]
