# Generated by Django 3.0.5 on 2020-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0012_auto_20200504_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsource',
            name='input_type',
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('NONE', 'None'), ('TEXTFIELD', 'Small text field'), ('TEXTAREA', 'Large text area')], default='NONE', max_length=9),
        ),
    ]
