# Generated by Django 3.0.5 on 2020-05-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0014_auto_20200504_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextAdventureChoiceDescription',
            fields=[
                ('from_adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfplatz.Adventure')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PathChoiceDescription',
            fields=[
                ('path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfplatz.Path')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golfplatz.Question'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pathcoverage',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golfplatz.Path'),
        ),
        migrations.AlterField(
            model_name='pathcoverage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
