# Generated by Django 3.0.5 on 2020-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0015_auto_20200520_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='points_for_max_grade',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=7),
            preserve_default=False,
        ),
    ]
