# Generated by Django 3.0.5 on 2020-05-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0016_auto_20200523_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='timerrule',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_rules', to='golfplatz.Adventure'),
        ),
    ]
