# Generated by Django 3.0.5 on 2020-05-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0017_auto_20200523_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='students',
        ),
        migrations.DeleteModel(
            name='PathCoverage',
        ),
    ]
