# Generated by Django 3.0.5 on 2020-05-26 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0018_auto_20200526_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishedAdventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure_started_time', models.DateTimeField()),
                ('time_elapsed_seconds', models.PositiveSmallIntegerField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golfplatz.Adventure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='done_by_students',
            field=models.ManyToManyField(through='golfplatz.AccomplishedAdventure', to=settings.AUTH_USER_MODEL),
        ),
    ]
