# Generated by Django 3.0.5 on 2020-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0019_auto_20200526_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('OPEN', 'Open question'), ('CLOSED', 'Closed question')], default='OPEN', max_length=6),
            preserve_default=False,
        ),
    ]
