# Generated by Django 3.0.5 on 2020-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0022_question_is_multiple_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='awaiting_tutor_grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointsource',
            name='is_auto_checked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
