# Generated by Django 3.0.5 on 2020-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0023_auto_20200630_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsource',
            name='is_auto_checked',
        ),
        migrations.AddField(
            model_name='question',
            name='is_auto_checked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='points_for_max_grade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
