# Generated by Django 3.0.5 on 2020-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0024_auto_20200718_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('TEXTFIELD', 'Small text field'), ('TEXTAREA', 'Large text area')], default='TEXTFIELD', max_length=9),
        ),
    ]
