# Generated by Django 3.0.5 on 2020-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0025_auto_20200910_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='has_time_limit',
        ),
        migrations.AddField(
            model_name='adventure',
            name='time_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='creating_completed',
            field=models.BooleanField(default=False),
        ),
    ]
