# Generated by Django 3.1.2 on 2020-10-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0026_auto_20200930_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishedAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('course_element_considered', models.CharField(choices=[('PLOT_PART', 'Plot part'), ('CHAPTER', 'Chapter')], max_length=10)),
                ('how_many', models.PositiveSmallIntegerField()),
                ('in_a_row', models.BooleanField()),
                ('condition_type', models.CharField(choices=[('SCORE', 'Score'), ('TIME', 'Time')], max_length=10)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('accomplished_by_students', models.ManyToManyField(through='golfplatz.AccomplishedAchievement', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='golfplatz.course')),
            ],
        ),
        migrations.CreateModel(
            name='AccomplishedChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_scored', models.DecimalField(decimal_places=3, max_digits=7)),
                ('average_time_taken_percent', models.PositiveSmallIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('time_completed', models.DateTimeField(default=None, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golfplatz.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accomplishedachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='golfplatz.achievement'),
        ),
        migrations.AddField(
            model_name='accomplishedachievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='done_by_students',
            field=models.ManyToManyField(through='golfplatz.AccomplishedChapter', to=settings.AUTH_USER_MODEL),
        ),
    ]
