# Generated by Django 3.1.2 on 2020-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0027_auto_20201015_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishedadventure',
            options={'ordering': ['adventure_started_time']},
        ),
        migrations.AddField(
            model_name='accomplishedadventure',
            name='applied_time_modifier_percent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomplishedadventure',
            name='total_points_for_questions_awarded',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomplishedchapter',
            name='average_time_taken_percent',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accomplishedchapter',
            name='points_scored',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='accomplishedchapter',
            name='time_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
