# Generated by Django 3.1.2 on 2020-10-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0029_auto_20201016_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishedchapter',
            options={'ordering': ['time_started']},
        ),
        migrations.AddField(
            model_name='accomplishedchapter',
            name='new_achievements_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
