# Generated by Django 3.1.2 on 2020-10-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0030_auto_20201019_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishedchapter',
            name='average_time_taken_percent',
        ),
    ]
