# Generated by Django 3.1.2 on 2020-10-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0031_remove_accomplishedchapter_average_time_taken_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishedchapter',
            name='new_achievements_count',
        ),
        migrations.AddField(
            model_name='accomplishedachievement',
            name='accomplished_in_chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='golfplatz.accomplishedchapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomplishedchapter',
            name='achievements_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accomplishedchapter',
            name='recalculating_score_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accomplishedchapter',
            name='total_score_recalculated',
            field=models.BooleanField(default=False),
        ),
    ]
