# Generated by Django 3.1.2 on 2020-10-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0032_auto_20201026_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfplatz.grade')),
            ],
        ),
        migrations.CreateModel(
            name='StudentImageAnswer',
            fields=[
                ('studentanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='golfplatz.studentanswer')),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('golfplatz.studentanswer',),
        ),
        migrations.CreateModel(
            name='StudentTextAnswer',
            fields=[
                ('studentanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='golfplatz.studentanswer')),
                ('text', models.TextField()),
            ],
            bases=('golfplatz.studentanswer',),
        ),
    ]
