# Generated by Django 3.1.2 on 2020-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0033_studentanswer_studentimageanswer_studenttextanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='max_points_possible',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('TEXTFIELD', 'Small text field'), ('TEXTAREA', 'Large text area'), ('IMAGE', 'Image')], default='TEXTFIELD', max_length=9),
        ),
    ]
