# Generated by Django 3.1.2 on 2020-11-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0034_auto_20201107_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_scored', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfplatz.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lower_threshold_percent', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfplatz.course')),
            ],
            options={
                'ordering': ['lower_threshold_percent'],
            },
        ),
        migrations.AlterField(
            model_name='adventure',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plotpart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SurpriseExercise',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='students',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='students',
            field=models.ManyToManyField(through='golfplatz.CourseGroupStudents', to=settings.AUTH_USER_MODEL),
        ),
    ]
