# Generated by Django 3.1.2 on 2020-11-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0035_auto_20201108_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='golfplatz.grade'),
        ),
    ]
