# Generated by Django 3.1.2 on 2020-11-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0036_auto_20201109_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_ranking_visibility_strategy',
            field=models.CharField(choices=[('RANKS_ONLY', 'Ranks only')], default='RANKS_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='coursegroupstudents',
            name='chapters_done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
