# Generated by Django 3.0.5 on 2020-11-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0037_auto_20201111_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishedadventure',
            name='is_fully_graded',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointsource',
            name='category',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('GENERIC', 'Generic lab exercise'), ('ACTIVENESS', 'Activeness'), ('TEST', 'Test'), ('HOMEWORK', 'Homework or project')], max_length=10),
        ),
    ]
