# Generated by Django 3.0.5 on 2020-11-16 20:25

from django.db import migrations, models
import golfplatz.models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0038_auto_20201115_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='access_code',
            field=models.CharField(default=golfplatz.models.get_random_access_code, max_length=8),
        ),
    ]
