# Generated by Django 3.0.5 on 2020-11-20 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0039_coursegroup_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='theme_color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-f]{6}$')]),
            preserve_default=False,
        ),
    ]
