# Generated by Django 3.0.5 on 2020-11-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0040_course_theme_color'),
        ('golfplatz', '0041_auto_20201122_2203'),
    ]

    operations = [
    ]
