# Generated by Django 3.0.5 on 2020-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0042_merge_20201125_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotpart',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
