# Generated by Django 3.0.5 on 2020-11-29 14:51

from django.db import migrations, models
import golfplatz.models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0043_plotpart_is_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.CharField(default=golfplatz.models.get_system_key, max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone_number',
        ),
    ]
