# Generated by Django 3.0.5 on 2020-12-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0044_auto_20201129_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='adventure_category_included',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('GENERIC', 'Generic lab exercise'), ('ACTIVENESS', 'Activeness'), ('TEST', 'Test'), ('HOMEWORK', 'Homework or project')], max_length=10, null=True),
        ),
    ]
