# Generated by Django 3.0.5 on 2020-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0045_achievement_adventure_category_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_ranking_visibility_strategy',
        ),
        migrations.AddField(
            model_name='course',
            name='ranking_mode',
            field=models.CharField(choices=[('FULL', 'Full'), ('PARTICIPANT_AND_TOP', 'Participant and top'), ('PARTICIPANT', 'Participant'), ('OFF', 'Off')], default='FULL', max_length=20),
        ),
    ]
