# Generated by Django 3.0.5 on 2020-12-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0045_achievement_adventure_category_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='max_points_possible',
        ),
    ]
