# Generated by Django 3.0.5 on 2020-12-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfplatz', '0046_auto_20201212_1245'),
        ('golfplatz', '0046_remove_adventure_max_points_possible'),
    ]

    operations = [
    ]
